# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sitemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('uts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-ts',),
            },
        ),
        migrations.CreateModel(
            name='valuesmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('uts', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mw3.sitemodel')),
            ],
            options={
                'ordering': ('-ts',),
            },
        ),
    ]
